### ISSUE TITLE
minelp textures

### ISSUE THREAD

**Issue by PCelestia** [Love-and-Tolerance/Love-and-Tolerance#69] opened 2020-05-05 00:53 UTC
these are textures that aren't present in the pack right now. i don't know if we intend to add them, so I'm just going to list all of them here. if we arent going to add it, mark it as complete. and unmark it if we are adding it to the pack

entity:
 - [ ] enderman
 - [ ] illager
 - [X] pony (doesn't look like it)
 - [ ] zombie villager
 - [X] Alex pony
 - [X] seapony
 - [X] steve pony
 - [X] wandering trader
 - [X] witch pony

gui:
 - [X] pony (the only thing that's there

mob:
 - [X] noskin alex
 - [X] noskin steve
 - [X] noskin seapony

models:
 - [X] antlers
 - [X] muffin
 - [X] saddlebags
 - [X] stetson

all files in minelp armor folder are present in l&t

these files present in armor, but not in minelp 4.0.9-1.15.2 (might want to remove them)
 - [ ] chainmail_layer_1_pony
 - [ ] chainmail_layer_2_pony
 - [ ] diamond_layer_1_pony
 - [ ] diamond_layer_2_pony
 - [ ] gold_layer_1_pony
 - [ ] gold_layer_2_pony
 - [ ] iron_layer_1
 - [ ] iron_layer_1_pony
 - [ ] iron_layer_2
 - [ ] iron_layer_2_pony
 - [ ] iron_layer_inner
 - [ ] iron_layer_outer
 - [ ] leather_layer_1_overlay_pony
 - [ ] leather_layer_1_pony
 - [ ] leather_layer_2_overlay_pony
 - [ ] leather_layer_2_pony

took this list from minelp 4.0.9-1.15.2

**Comment by Sollace** [comment] 2020-05-05 06:38
Duplicate of #26

**Comment by PCelestia** [comment] 2020-05-05 06:52
this is not a duplicate of #26, there are things in here that aren’t present in #26

**Comment by Sollace** [comment] 2020-05-05 07:06
The scope of #26 covers all of the MineLP textures, listed or no. This one will be listed under there for the mentions.

Please do not open it again.

**Closed by Sollace** 2020-05-05 07:06 UTC
