### ISSUE TITLE
minelp armor

### ISSUE THREAD

**Issue by PCelestia** [Love-and-Tolerance/Love-and-Tolerance#68] opened 2020-05-04 22:45 UTC
ive seen an issue about minelp armor textures in L&T rendering as invalid, so might as well check those

confirmed needs fixing:
 - [ ] iron chestplate

confirmed doesn't need fixing:
 - [X] leather chestplate

I don't know yet:
 - [ ] leather helmet
 - [ ] leather leggings
 - [ ] leather boots
 - [ ] chainmail helmet
 - [ ] chainmail chestplate
 - [ ] chainmail leggings
 - [ ] chainmail boots
 - [ ] iron helmet
 - [ ] iron leggings
 - [ ] iron boots
 - [ ] diamond helmet
 - [ ] diamond chestplate
 - [ ] diamond leggings
 - [ ] diamond boots
 - [ ] gold helmet
 - [ ] gold chestplate
 - [ ] gold leggings
 - [ ] gold boots
 - [ ] turtle shell

eventually:
 - [ ] netherite helmet
 - [ ] netherite chestplate
 - [ ] netherite leggings
 - [ ] netherite boots

**Comment by Sollace** [comment] 2020-05-05 06:37
Duplicate of #26

**Comment by PCelestia** [comment] 2020-05-05 06:50
i don’t think this is a duplicate, there are no armor related things in #26, and also it would be nice to have a checklist of all the different armor pieces to check

**Closed** 2020-05-05 07:06 UTC
Labels: critical
